#!/usr/bin/env python3
import json
import os
import sys
import time
import urllib.request
import urllib.parse

AGENT_ID = "nemo-code"
POLL_INTERVAL = 5
SCRATCH_DIR = os.path.join(os.path.dirname(__file__), "..", "SCRATCH")
ORCHESTRATOR_URL = "http://localhost:3060/api/v1/swarm/task"
PROJECT_BASE = os.path.join(os.path.dirname(__file__), "..")

sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))
from orchestrator.logger import SwarmLogger
from orchestrator.llm_client import ask

logger = SwarmLogger(agent_id=AGENT_ID)
os.makedirs(SCRATCH_DIR, exist_ok=True)


def send_webhook(status, payload):
    body = json.dumps({"agent_id": AGENT_ID, "status": status, **payload}).encode()
    try:
        req = urllib.request.Request(
            ORCHESTRATOR_URL, data=body,
            headers={"Content-Type": "application/json"}, method="POST"
        )
        urllib.request.urlopen(req, timeout=10)
    except Exception as e:
        logger.warn(f"Webhook failed: {e}")


def generate_code(task_prompt):
    prompt = f"""Generate code for the following task:

{task_prompt}

Rules:
- Output code blocks with a language tag (e.g. ```python)
- Include a brief header comment describing the file
- If multiple files, output each file block with a comment path like `# FILE: path/to/file`
- Use modern, clean, idiomatic patterns
- Do NOT include installation instructions
"""
    logger.info(f"Calling LLM for code generation: {task_prompt[:80]}...")
    raw = ask(prompt, role="coder")
    logger.info(f"LLM response ({len(raw)} chars)")
    return raw


def extract_and_save(raw, task_id):
    files = {}
    current_file = None
    current_lines = []

    for line in raw.split("\n"):
        if line.startswith("# FILE:") or line.startswith("// FILE:"):
            if current_file:
                files[current_file] = "\n".join(current_lines)
            current_file = line.split(":", 1)[1].strip()
            current_lines = []
        elif line.startswith("```"):
            pass
        else:
            current_lines.append(line)
    if current_file:
        files[current_file] = "\n".join(current_lines)

    if not files:
        path = os.path.join(SCRATCH_DIR, f"output_{task_id}.py")
        code = raw.strip().strip("```").strip()
        if code.startswith("python\n"):
            code = code[7:]
        with open(path, "w", encoding="utf-8") as f:
            f.write(f"# Generated by {AGENT_ID} | task={task_id}\n{code}\n")
        files[path] = code
        logger.info(f"Saved fallback output to {path}")
    else:
        for rel_path, content in files.items():
            abs_path = os.path.join(SCRATCH_DIR, rel_path)
            os.makedirs(os.path.dirname(abs_path), exist_ok=True)
            with open(abs_path, "w", encoding="utf-8") as f:
                f.write(f"# Generated by {AGENT_ID} | task={task_id}\n{content}\n")
            logger.info(f"Saved {rel_path} ({len(content)} chars)")

    return list(files.keys())


def poll_for_task():
    url = f"{ORCHESTRATOR_URL}?agent_id={urllib.parse.quote(AGENT_ID)}"
    try:
        req = urllib.request.Request(url)
        with urllib.request.urlopen(req, timeout=10) as resp:
            return json.loads(resp.read().decode("utf-8"))
    except Exception:
        return None


def run():
    logger.info("Agent started")
    send_webhook("started", {"msg": "Agent online"})

    while True:
        task = poll_for_task()
        if task:
            task_id = task.get("id", "unknown")
            prompt = task.get("prompt", task.get("data", ""))
            logger.info(f"Processing task {task_id}: {prompt[:80]}")

            try:
                raw_code = generate_code(prompt)
                saved = extract_and_save(raw_code, task_id)
                send_webhook("completed", {"task_id": task_id, "files": saved})
                logger.info(f"Done: {saved}")
            except Exception as e:
                logger.error(f"Failed: {e}")
                send_webhook("failed", {"task_id": task_id, "error": str(e)})
        else:
            time.sleep(POLL_INTERVAL)


if __name__ == "__main__":
    run()
