from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[2]

ARCHIVE_ROOT = PROJECT_ROOT / "99_ARCHIVE" / "deepkeep"
DB_PATH = ARCHIVE_ROOT / "registry.db"
TRESOR_PATH = PROJECT_ROOT / "[DEEPKEEP]"
LOG_PATH = ARCHIVE_ROOT / "audit.log"

RETENTION_DAYS_FIRST = 7
RETENTION_DAYS_SECOND = 30

SCOPE_EXCEPTIONS = {ARCHIVE_ROOT, TRESOR_PATH}

ARCHIVE_SUBDIR_FORMAT = "%Y-%m-%d"

REGISTRY_SCHEMA_VERSION = 1
